name: design_system
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/email_icon.svg
    - assets/github.svg
    - assets/linkedin.svg